[test]
timeout = 18000
# zelda root directory
base_dir = /data/projects/zelda

[crawler]
chromedriver_path = ../chromedriver

[fuzzer]
# timeout for the fuzzing process for one URL
fuzz_timeout = 5
process = 5
exploration = 1
importance = 0.6
content_change = 0.1

